services:
  app:
    build: .
    container_name: astro-auth-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - dhwaniastro-net

networks:
  dhwaniastro-net:
    external: true