services:
  astro-auth-service:
    build: .
    container_name: astro-auth-service
    restart: always

    env_file:
      - .env

    ports:
      - "8008:8008"

    volumes:
      # Shared uploads folder on host
      - /var/www/chat-uploads:/shared/chat-uploads

    networks:
      - dhwaniastro-net

    mem_limit: 512m
    memswap_limit: 512m

networks:
  dhwaniastro-net:
    external: true