services:
  astro-auth-service:
    build: .
    container_name: astro-auth-service
    restart: always   #  auto restart on crash
    env_file:
      - .env
    ports:
      - "8008:8008"
    networks:
      - dhwaniastro-net
    mem_limit: 50m     #  memory limit
    memswap_limit: 50m #  prevent swap (force crash)

networks:
  dhwaniastro-net:
    external: true